#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
using Core.Services;

namespace Core
{
    public static class SignalDispatch
    {
        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId) =>
            SignalService.AddSignal(signalId);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0) =>
            SignalService.AddSignal(signalId, arg0);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1) =>
            SignalService.AddSignal(signalId, arg0, arg1);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2, object arg3) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2, arg3);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2, object arg3, object arg4) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2, arg3, arg4);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2, arg3, arg4, arg5);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2, arg3, arg4, arg5, arg6);

        /// <summary>
        /// This method should only be called by autogenerated class called Signals.g.cs.
        /// </summary>
        public static void Intercept(int signalId,
            object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) =>
            SignalService.AddSignal(signalId, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }
}